language: generic

sudo: required
services:
  - docker


before_install:
  - docker build -t yang/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true yang/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-test"
  env: "Dockertest-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-090460596260"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"